name: Selenium Tests

on:
  workflow_dispatch:
  schedule:
    - cron: '40 */2 * * *'

jobs:
  selenium-tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cancel Workflow Action
      uses: styfle/cancel-workflow-action@0.12.0
      with:
            all_but_latest: true
            access_token: ${{ github.token }}
        
    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@v2
      with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 0
    

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'  # Choose the Python version you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium

    - name: Download and configure web driver (ChromeDriver in this example)
      run: |
        wget https://edgedl.me.gvt1.com/edgedl/chrome/chrome-for-testing/121.0.6167.85/linux64/chromedriver-linux64.zip
        unzip chromedriver-linux64.zip
        sudo mv chromedriver-linux64/chromedriver /usr/local/bin/
        sudo chmod +x /usr/local/bin/chromedriver

    - name: Run Selenium tests
      run: |
        python main.py
